# Users
## Create new user
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "newUser@koko.com",
  "avatar": "torrance.png",
  "name": "Jo",
  "password": "jolololo",
  "type": "pro"
}

###
## Login user
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "newUser@koko.com",
  "password": "jolololo"
}


###
## upload avatar

POST http://localhost:5000/users/68efd98fd8d36eafd6f6bbfb/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="image.png"
Content-Type: image/png

< C:\Users\User\Desktop\images.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5ld1VzZXJAa29rby5jb20iLCJuYW1lIjoiSm8iLCJpZCI6IjY5MzU4ZGI3NjVhZTg4OTM1Yjk2ZmUyYiIsImlhdCI6MTc2NTEyMTk3OCwiZXhwIjoxNzY1MTIyODc4fQ.v--_UCEyxGWy_SWm_m4MF8S3KbIKc5ZLX4GHAxi-yJo

###
