# Offers
## Get list of offers
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

GET http://localhost:5000/offers/6910c5889ba0a0439073018e HTTP/1.1
Content-Type: application/json

###

GET http://localhost:5000/offers/premium/Cologne HTTP/1.1
Content-Type: application/json

###